# Generated by Django 5.0.3 on 2024-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/image/')),
            ],
        ),
    ]
